apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bazaario
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # CI/CD replaces this tag - see .github/workflows/ci.yml and k8s/base/kustomization.yaml
          image: 256097482448.dkr.ecr.ap-south-1.amazonaws.com/bazaario-backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: bazaario-app-secrets # populated by ExternalSecret from AWS Secrets Manager
          env:
            - name: PORT
              value: "5000"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: bazaario
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
