apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: bazaario
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::256097482448:role/bazaario-dev-external-secrets"

---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: bazaario
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazaario-app-secrets
  namespace: bazaario
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: bazaario-app-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: bazaario-dev-app-secrets/app-secrets