apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: bazaario
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1 # must match var.aws_region
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets
  annotations:
    # Replace with the external_secrets_role_arn Terraform output
    eks.amazonaws.com/role-arn: "arn:aws:iam::256097482448:role/bazaario-dev-external-secrets"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bazaario-app-secrets
  namespace: bazaario
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: bazaario-app-secrets # this is the k8s Secret the backend Deployment reads from
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: bazaario-dev-app-secrets/app-secrets # must match the Secrets Manager secret name from Terraform output
